spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/demo
  quartz:
    #相关属性配置
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: default
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.simpl.RAMJobStore
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 10000
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: MEMORY
server:
  port: 8888
  servlet:
    context-path: /demo
    #初始化表结构
    #jdbc:
      #initialize-schema: never
